# 第二章 线性代数

In [3]:
import numpy as np

In [9]:
# 标量
s =  5
# 向量 
v=np.array([1,2])

In [10]:
# 矩阵 
m = np.array([[1,2], [3,4]]) 

In [24]:
# 张量 
t = np.array([ 
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]], 
    [
        [11,12,13],
        [14,15,16],
        [17,18,19]], 
    [
        [21,22,23],
        [24,25,26],
        [27,28,29]], 
    [
        [121,122,123],
        [124,125,126],
        [127,128,129]], 
]) 

In [25]:
print("标量: " + str(s)) 
print("向量: " + str(v)) 
print("矩阵: " + str(m)) 
print("张量: " + str(t))

标量: 5
向量: [1 2]
矩阵: [[1 2]
 [3 4]]
张量: [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]]

 [[ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]

 [[121 122 123]
  [124 125 126]
  [127 128 129]]]


In [26]:
print(t.shape)

(4, 3, 3)


In [28]:
t.transpose() 

array([[[  1,  11,  21, 121],
        [  4,  14,  24, 124],
        [  7,  17,  27, 127]],

       [[  2,  12,  22, 122],
        [  5,  15,  25, 125],
        [  8,  18,  28, 128]],

       [[  3,  13,  23, 123],
        [  6,  16,  26, 126],
        [  9,  19,  29, 129]]])

In [31]:
print(t.transpose().shape)

(3, 3, 4)


In [36]:
A = np.array([[1.0,2.0],[1.0,0.0],[2.0,3.0]]) 
A_t = A.transpose() 
print("A:", A) 
print("A 的转置:", A_t)
print("A.shape:",A.shape)
print("A_t.shape:",A_t.shape)

A: [[1. 2.]
 [1. 0.]
 [2. 3.]]
A 的转置: [[1. 1. 2.]
 [2. 0. 3.]]
A.shape: (3, 2)
A_t.shape: (2, 3)


In [38]:
a = np.array([[1.0,2.0],[3.0,4.0]]) 
b = np.array([[6.0,7.0],[8.0,9.0]])
print("矩阵相加：", a + b)

矩阵相加： [[ 7.  9.]
 [11. 13.]]


In [39]:
m1 = np.array([[1.0,3.0],[1.0,0.0]])
m2 = np.array([[1.0,2.0],[5.0,0.0]])
print("按矩阵乘法规则：", np.dot(m1, m2))
print("按逐元素相乘：", np.multiply(m1, m2))
print("按逐元素相乘：", m1*m2)
v1 = np.array([1.0,2.0])
v2 = np.array([4.0,5.0])
print("向量内积：", np.dot(v1, v2))


按矩阵乘法规则： [[16.  2.]
 [ 1.  2.]]
按逐元素相乘： [[1. 6.]
 [5. 0.]]
按逐元素相乘： [[1. 6.]
 [5. 0.]]
向量内积： 14.0


In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
A = [[1.0,2.0],[3.0,4.0]] 
A_inv = np.linalg.inv(A) 
print("A 的逆矩阵", A_inv)
print(A_inv.dot(A))

A 的逆矩阵 [[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


In [48]:
a = np.array([1.0,3.0]) 
print("向量 2 范数", np.linalg.norm(a,ord=2)) 
print("向量 1 范数", np.linalg.norm(a,ord=1)) 
print("向量无穷范数", np.linalg.norm(a,ord=np.inf))

向量 2 范数 3.1622776601683795
向量 1 范数 4.0
向量无穷范数 3.0


In [51]:
a = np.array([[1.0,3.0],[2.0,1.0]])
print("向量 2 范数", np.linalg.norm(a,ord=2)) 
print("向量 1 范数", np.linalg.norm(a,ord=1)) 
print("向量无穷范数", np.linalg.norm(a,ord=np.inf))
print("矩阵 F 范数", np.linalg.norm(a,ord="fro"))

向量 2 范数 3.618033988749895
向量 1 范数 4.0
向量无穷范数 4.0
矩阵 F 范数 3.872983346207417
